### ISSUE TITLE
Feedback for new WebAssembly opaque package based on opaque-ke

### ISSUE THREAD

**Issue by nikgraf** [marucjmar/opaque-wasm#12]
Hey, opaque-wasm was a great inspiration and served us well, but since the OPAQUE protocol was such an essential piece in our project we decided to build our own package.

I wanted to ask if any of you have feedback regarding the API design or any other concerns.

I also made a comparison table to highlight the differences between `opaque-wasm` and `@serenity-kit/opaque`. see https://opaque-documentation.netlify.app/docs/faq#how-does-it-compare-to-opaque-wasm

**Comment by marucjmar** [comment]
Hello, 

I'm glad that someone has taken further steps of development opaque-ke protocol in WASM. The use of the functional/stateless paradigm appeals to me very much. I am willing to add an annotation of your library in this repo. If you want add PR to Readme.Me with adnotation. Unfortunately, I do not have enough time to develop the current library. 

I looked at your library and it looks really promising. 

According to this issue #2 , In my opinion, all opaque-qe operations should happen outside the main browser thread.

**Comment by nikgraf** [comment]
Thanks a lot @marucjmar, really glad you think it looks promising and thanks for the offer to add an annotation :)

Will open a PR soon.

Regarding #2: thanks for the hint! This is more a bundler issue how to package and load WebAssembly (should be an async module). We solved it by inlining the WASM code as base64 and load it on module initialisation and expose a ready function. afaik If this proposal passes and gets implemented you can load WASM modules sync and then we can drop our inlining. A bit more details are documented here: https://opaque-documentation.netlify.app/docs/architecture-decisions#why-inline-the-wasm-code

**Comment by nikgraf** [comment]
After a successful security audit of our project I now felt comfortable to actively recommend it and created a PR to link to it: https://github.com/marucjmar/opaque-wasm/pull/13
