### ISSUE TITLE
64-byte session key

### ISSUE THREAD

**Issue by ThierrySans** [marucjmar/opaque-wasm#3]
When I run the `js-test/test.mjs`, the session key obtained is 64 bytes long (`Uint8Array(64)`). However, the opaque-ke documentation says that we should obtain a 32-byte session key. 

Am I missing something here? Where does this discrepancy come from?

**Comment by Hawkheart** [comment]
The `opaque-ke` documentation appears to be incorrect to me; the session key length is not always 32 bytes. It appears to depend on the chosen parameters, and the parameters chosen by these bindings (SHA-512 in particular) lead to 64-byte keys.

**Comment by marucjmar** [comment]
Thanks for report, 
I'll check today, but @Hawkheart may be right :+1:

**Comment by ThierrySans** [comment]
It makes sense. Thank you very much!
