### ISSUE TITLE
Update opaque-ke from 0.6.0 to 0.6.1

### ISSUE THREAD

**Issue by kevinlewi** [marucjmar/opaque-wasm#6]
From https://github.com/novifinancial/opaque-ke/issues/264, a new version of opaque-ke was released, since 0.6.0 is broken. Mind updating the dependency to 0.6.1 at your convenience? Thanks!

**Comment by marucjmar** [comment]
Thanks, 

New version released and published(in npm) https://github.com/marucjmar/opaque-wasm/releases/tag/1.1.0
