### ISSUE TITLE
New pre-release based on the 2.0.0 version

### ISSUE THREAD

**Issue by nikgraf** [marucjmar/opaque-wasm#7]
I was wondering if you consider or would be open to do a pre-release based on the opaque-ke pre-release https://github.com/novifinancial/opaque-ke/releases/tag/v2.0.0-pre.2

**Comment by sheganinans** [comment]
@nikgraf #8 solves this issue

**Comment by marucjmar** [comment]
@nikgraf @sheganinans Version 2.0.0 has been published.
